"""Offline paired semantic parity report. No oracle or engine is run by this tool.

Input is JSONL with source/rust Position envelopes and complete comparison
artifacts generated by their respective runners. Missing evidence is never PASS.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from rule_projection import (
    Verdict, compare_exact_distribution, compare_positions,
    compare_sample_distribution,
)

MAX_CASES = 10_000
MAX_LINE_BYTES = 16 * 1024 * 1024


def _action_meaning(action: Any) -> str:
    if not isinstance(action, dict):
        raise ValueError("legal action must be an object")
    payload = action.get("payload", action)
    if not isinstance(payload, dict):
        raise ValueError("legal action payload must be an object")
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def _legal_meanings(actions: Any) -> list[str]:
    if not isinstance(actions, list):
        raise ValueError("legal actions must be a complete array")
    return sorted(_action_meaning(action) for action in actions)


def compare_case(case: dict[str, Any]) -> dict[str, Any]:
    checks: dict[str, dict[str, str]] = {}
    for key in ("name", "source", "rust", "sourceActions", "rustActions",
                "sourceObservations", "rustObservations", "sourceRejection", "rustRejection",
                "sourceAction", "rustAction"):
        if key not in case:
            return {"name": case.get("name"), "status": "UNSUPPORTED",
                    "reason": f"missing required evidence: {key}", "checks": checks}
    checks["position"] = compare_positions(case["source"], case["rust"]).as_dict()
    for side in ("sourceObservations", "rustObservations"):
        if not isinstance(case[side], dict) or set(case[side]) != {"white", "black"}:
            return {"name": case["name"], "status": "UNSUPPORTED",
                    "reason": f"{side} must contain both viewers", "checks": checks}
    for side in ("sourceRejection", "rustRejection"):
        result = case[side]
        if not isinstance(result, dict) or result.get("rejected") is not True or result.get("unchanged") is not True:
            return {"name": case["name"], "status": "MISMATCH",
                    "reason": f"{side} did not reject without mutation", "checks": checks}
    try:
        source_actions = _legal_meanings(case["sourceActions"])
        rust_actions = _legal_meanings(case["rustActions"])
        source_action = _action_meaning(case["sourceAction"])
        rust_action = _action_meaning(case["rustAction"])
    except ValueError as error:
        return {"name": case["name"], "status": "UNSUPPORTED",
                "reason": str(error), "checks": checks}
    if source_action not in source_actions or rust_action not in rust_actions:
        return {"name": case["name"], "status": "UNSUPPORTED",
                "reason": "selected action is absent from a legal action list", "checks": checks}
    checks["selectedAction"] = Verdict(
        "PASS" if source_action == rust_action else "MISMATCH",
        "selected action meanings agree" if source_action == rust_action else "selected action meanings differ",
        "paired-artifact-v1").as_dict()
    checks["legalActions"] = Verdict(
        "PASS" if source_actions == rust_actions else "MISMATCH",
        "complete legal action meanings agree" if source_actions == rust_actions else "legal action meanings differ",
        "paired-artifact-v1").as_dict()
    for key, source_key, rust_key in (
        ("observations", "sourceObservations", "rustObservations"),
        ("rejection", "sourceRejection", "rustRejection"),
    ):
        source, rust = case[source_key], case[rust_key]
        checks[key] = Verdict("PASS" if source == rust else "MISMATCH",
                              "paired values agree" if source == rust else "paired values differ",
                              "paired-artifact-v1").as_dict()
    distribution = case.get("distribution")
    if not isinstance(distribution, dict):
        checks["distribution"] = Verdict("UNSUPPORTED", "joint outcome distribution absent",
                                         "paired-artifact-v1").as_dict()
    elif distribution.get("kind") == "exact" and distribution.get("complete") is True:
        checks["distribution"] = compare_exact_distribution(
            distribution.get("source", {}), distribution.get("rust", {})).as_dict()
    elif distribution.get("kind") == "sample" and distribution.get("conditionedOn"):
        checks["distribution"] = compare_sample_distribution(
            distribution.get("source", {}), distribution.get("rust", {}),
            tolerance=distribution.get("tolerance", 0.0),
            alpha=distribution.get("alpha", 0.01)).as_dict()
    else:
        checks["distribution"] = Verdict("UNSUPPORTED", "distribution requires a known kind, complete exact support, or a sample conditioning key",
                                         "paired-artifact-v1").as_dict()
    statuses = {check["status"] for check in checks.values()}
    status = next((item for item in ("MISMATCH", "UNSUPPORTED", "INCONCLUSIVE") if item in statuses), "PASS")
    return {"name": case["name"], "status": status, "checks": checks}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pairs", type=Path, required=True, help="paired external JSONL input")
    parser.add_argument("--report", type=Path, required=True, help="external summary JSON output")
    args = parser.parse_args()
    cases = []
    with args.pairs.open("rb") as source:
        for number, raw in enumerate(source, 1):
            if number > MAX_CASES or len(raw) > MAX_LINE_BYTES:
                raise ValueError(f"case budget exceeded at line {number}")
            item = json.loads(raw)
            if not isinstance(item, dict):
                raise ValueError(f"line {number} must be an object")
            cases.append(compare_case(item))
    if not cases:
        raise ValueError("paired input is empty")
    statuses = {case["status"] for case in cases}
    overall = next((item for item in ("MISMATCH", "UNSUPPORTED", "INCONCLUSIVE") if item in statuses), "PASS")
    report = {"contract": "augment-rule-semantic-v1", "status": overall, "cases": cases,
              "note": "PASS is bounded by supplied evidence; sampled PASS is statistical only"}
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"status": overall, "caseCount": len(cases), "report": str(args.report)},
                     ensure_ascii=False))
    return 0 if overall == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
